### ISSUE TITLE
Not join pdfs to one

### ISSUE THREAD

**Issue by evgenii** [blambeau/pdf-toolkit#1]
Hi, 

I've use this gem for join pdfs to one, but it isn't work for me.

```
result = PDF::Toolkit.pdftk(*%w(foo.pdf bar.pdf cat output baz.pdf))
TypeError: can't convert Symbol into String
    from /home/evgenii/.rvm/gems/ruby-1.9.3-p125@StopLossConnect/bundler/gems/pdf-toolkit-2b91bf640b33/lib/pdf/toolkit/native.rb:42:in `system'
    from /home/evgenii/.rvm/gems/ruby-1.9.3-p125@StopLossConnect/bundler/gems/pdf-toolkit-2b91bf640b33/lib/pdf/toolkit/native.rb:42:in `call_program'
from /home/evgenii/.rvm/gems/ruby-1.9.3-p125@StopLossConnect/bundler/gems/pdf-toolkit-2b91bf640b33/lib/pdf/toolkit/native.rb:15:in `pdftk'
    from (irb):3
    from /home/evgenii/.rvm/gems/ruby-1.9.3-p125@StopLossConnect/gems/railties-3.2.1/lib/rails/commands/console.rb:47:in `start'
    from /home/evgenii/.rvm/gems/ruby-1.9.3-p125@StopLossConnect/gems/railties-3.2.1/lib/rails/commands/console.rb:8:in `start'
    from /home/evgenii/.rvm/gems/ruby-1.9.3-p125@StopLossConnect/gems/railties-3.2.1/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

So, I've change all call_program(:pdftk,_args, &block) to call_program('pdftk',_args, &block) and it's works...
Also it would be cool if position of pdftk binary file can be configured for example form initializer...

Thanks

**Comment by blambeau** [comment]
Yep, I also experimented this a few weeks ago.

Don't hesitate to send a pull request. Otherwise I'll fix it ASAP myself.

**Comment by blambeau** [comment]
Recently fixed by another pull request.
